name: autos_villa_rosa_app
description: Una aplicación para gestionar coches en venta.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.10.3
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  pdf: ^3.11.1
  fluttertoast: ^9.0.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  universal_html: ^2.2.4
  provider: ^6.1.2
  table_calendar: ^3.1.2
  file_picker: ^10.3.3
  uuid: ^4.5.1
  printing: ^5.13.3
  http: ^1.2.2
  flutter_pdfview: ^1.4.3
  flutter_image_compress: ^2.0.0
  cached_network_image: ^3.3.1
  connectivity_plus: ^7.0.0
  timezone: ^0.10.1
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/LiberationSans-Regular.ttf
    - assets/fonts/LiberationSans-Bold.ttf